name: Terraform apply

on:
  push:
    branches:
      - main
    paths:
      - terraform/**
      - .github/workflows/terraform*
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
  DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}

jobs:
  terraform_apply:
    runs-on: ubuntu-22.04
    name: Terraform apply
    steps:
      - uses: actions/checkout@v4

      - name: Terraform apply
        uses: jonaskop/custom-github-actions/terraform-apply@main
        with:
          terraform-cloud-token: ${{ secrets.TF_API_TOKEN }}
          working-directory: ./terraform
