name: Terraform plan

on:
  pull_request:
    paths:
      - terraform/**
      - .github/workflows/terraform*
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
  DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}

jobs:
  terraform_plan:
    runs-on: ubuntu-22.04
    name: Terraform plan
    steps:
      - uses: actions/checkout@v4

      - name: Terraform plan
        uses: jonaskop/custom-github-actions/terraform-plan@main
        with:
          terraform-cloud-token: ${{ secrets.TF_API_TOKEN }}
          working-directory: ./terraform
